config/routes.rb
Nicabarometro2::Application.routes.draw do
  get "departments/index"
  devise_for :users
  get "weathers/index"
  resources :usuarios, :controller => "users", :as => "users"

  root 'weathers#index'

  get 'historial' => 'weathers#history'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, Weather
      can :read, PagesController
      can :read, Forecast
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :weathers
  has_many :forecasts
end

app/models/forecast.rb
class Forecast < ActiveRecord::Base
  belongs_to :department
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/weather.rb
class Weather < ActiveRecord::Base
  belongs_to :department

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :flash => { :danger => exception.message } #  :alert =>
  end

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :current_password, :password_confirmation, :password, :email)}
  end


end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    Department.all
  end

  def show

  end

  def edit

  end

  def update

  end

  def destroy

  end




  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @department = Department.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def department_params
    params.require(:department).permit(:name, :query)
  end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def alerts

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user), notice: 'User was successfully created.'
    else
      render_errors @user
    end
  end

  # PATCH/PUT /users/1
  def update
    parms = user_params
    if parms[:password].blank? && parms[:password_confirmation].blank?
      parms.except!(:password, :password_confirmation)
    end

    if @user.update(parms)
      redirect_to user_url(@user), notice: 'User was successfully updated.'
    else
      render_errors @user
    end
  end

   # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController


  def index
    #Por el momento, el departamento de Managua aparecería por defecto en caso que no se seleccione otro departamento
    @weather = params[:weather] || Weather.where(department_id: 9).last
    @forecasts = Forecast.all
    @departments = Department.all
  end

  def history
    @weathers_last_week = Weather.where(:created_at => 1.week.ago...Time.now)
    @weathers_last_month = Weather.where(:created_at => 1.month.ago...Time.now)

  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/departments/index.html.erb
<h1>Departments#index</h1>
<p>Find me in app/views/departments/index.html.erb</p>

app/views/layouts/_header.html.erb
<div class="container-fluid head-bar">
  <%= image_tag("topbg.png")%>
</div>

<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
  <h3>Menu</h3>
  <a><%= link_to 'Nicabarómetro', root_path %></a>
  <a href="#">Alertas</a>
  <a><%= link_to 'Historial', historial_path %></a>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuario <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <% if user_signed_in? %>
          <li><%= link_to current_user.name, edit_user_registration_path  %></li>
          <li class="divider"></li>
          <li>

            <%= link_to t("nav.sign_out_link"), destroy_user_session_path, method: :delete %>
          </li>
      <% else %>
          <li><%= link_to t("nav.sign_in_link"), new_user_session_path %></li>
      <% end %>
    </ul>
  </li>
</nav>
<div class="container chead">
  <div class="row">
    <div class="col-md-1">
      <span id="showLeftPush" class="btn btn-info menu"><%= image_tag("menu.png") %></span>
    </div>
    <div class="col-md-11">
      <h3>Nica-Barómetro</h3>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nicabarómetro</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="cbp-spmenu-push">

  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <%= value %></div>
    <% end %>
    <%= yield %>
  </div>



  <script>
      var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
        menuRight = document.getElementById( 'cbp-spmenu-s2' ),
        showLeftPush = document.getElementById( 'showLeftPush' ),
        showRightPush = document.getElementById( 'showRightPush' ),
        body = document.body;

      
      showLeftPush.onclick = function() {
        classie.toggle( this, 'active' );
        classie.toggle( body, 'cbp-spmenu-push-toright' );
        classie.toggle( menuLeft, 'cbp-spmenu-open' );
        disableOther( 'showLeftPush' );
      };

      function disableOther( button ) {        
        if( button !== 'showLeftPush' ) {
          classie.toggle( showLeftPush, 'disabled' );
        }
        if( button !== 'showRightPush' ) {
          classie.toggle( showRightPush, 'disabled' );
        }
      }
  </script>
  <script>
      var icons = new Skycons(),
//      icons.add("partlycloudy", Skycons.PARTLY_CLOUDY_DAY);
//      skycons.add(document.getElementById("partlycloudy"), Skycons.RAIN);


      list  = [
            "clear-day", "clear-night", "partly-cloudy-day",
            "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
            "fog"
          ],

          i;

      list_names = ["clear", "clear", "partlycloudy", "partlycloudy", "cloudy", "rain", "snow", "tstorms", "mostlycloudy", "fog"];

      for(i = list.length; i--; )
        icons.set(list_names[i], list[i]);

      icons.play();
    </script>
</body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>Starting the awesome!</h1>
  <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
  <p><a class="btn btn-lg btn-info" href="#" role="button">Suscríbete</a></p>
</div>

<h1>Hello :)</h1>
 <p>The current temp in <%= Department.first.name %> is <%= Department.first.weathers.first.temperature %> Cº</p>

app/views/users/_form.html.erb
<h2>Usuario</h2>

<%= form_for(@user) do |f| %>

    <div> <%= f.label :name %><br />
      <%= f.text_field :name %> </div>

    <div><%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %></div>

    <div><%= f.label 'Admin?' %> <br />
      <%= f.check_box :admin %> </div>

    <div><%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "off" %></div>

    <div><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

    <div><%= f.submit "Crear Usuario" %></div>
<% end %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
  <li>  <%= user.name %> </li>
  <li>  <%= user.email %> </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form" %>

app/views/weathers/history.html.erb
<h1> Historial </h1>

app/views/weathers/index.html.erb
<h2>RIGHT NOW!</h2>
<figure class="icons">
  <canvas id="<%= @weather.icon %>" width="84" height="84">
  </canvas>
</figure>

<h1>Estado actual del clima para <%= @weather.department.name %> </h1>

<ul>
  <li>Temperatura: <%= @weather.temperature %></li>
  <li>Humedad: <%= @weather.humidity.to_i %> %</li>

</ul>